namespace Global.TradingPlatform.Streamer
{
    public class Order
    {
        public int OrderID { get; set; }
        public Guid ClordID { get; set; }
        public string Symbol { get; set; }
        public string Side { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
        public int ExecutedQuantity { get; set; }
        public int RemainingQuantity { get; set; }
        public string CreatedBy { get; set; }
    }
    public class Execution
    {
        public int ExecutionID { get; set; } // identity ID in DB
        public int OrderID { get; set; } // FK
        public Guid OperationNumber { get; set; } // generated by market

        public int OrderQty { get; set; }
        public int LastShares { get; set; }
        public int CumulativeQty { get; set; }
        public int LeavesQuantity { get; set; }

        public string Status { get; set; } // Accpeted, PartiallyFilled, Filled, Cancelled

        public DateTime OperationTime { get; set; }

        // Navigation property
        public Order Order { get; set; }
    }
}
